[2024-01-23T17:02:38.750+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:02:38.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:02:38.752+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:02:38.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:02:38.767+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:02:38.765+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 4, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:02:38.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:02:38.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.032 seconds
[2024-01-23T17:03:09.139+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:03:09.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:03:09.145+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:03:09.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:03:09.160+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:03:09.159+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 4, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:03:09.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:03:09.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
[2024-01-23T17:03:39.477+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:03:39.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:03:39.480+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:03:39.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:03:39.500+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:03:39.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 4, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:03:39.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:03:39.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.041 seconds
[2024-01-23T17:04:09.846+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:04:09.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:04:09.850+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:04:09.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:04:09.867+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:04:09.866+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 4, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:04:09.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:04:09.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.047 seconds
[2024-01-23T17:04:40.210+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:04:40.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:04:40.216+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:04:40.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:04:40.235+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:04:40.234+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 4, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:04:40.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:04:40.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.064 seconds
[2024-01-23T17:05:10.538+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:05:10.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:05:10.543+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:05:10.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:05:10.560+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:05:10.559+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 4, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:05:10.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:05:10.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2024-01-23T17:05:40.870+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:05:40.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:05:40.873+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:05:40.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:05:40.945+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:05:40.944+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:05:40.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:05:40.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.093 seconds
[2024-01-23T17:06:11.248+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:06:11.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:06:11.252+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:06:11.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:06:11.296+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:06:11.294+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:06:11.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:06:11.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.085 seconds
[2024-01-23T17:06:41.628+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:06:41.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:06:41.634+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:06:41.633+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:06:41.698+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:06:41.696+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:06:41.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:06:41.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.100 seconds
[2024-01-23T17:07:11.982+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:07:11.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:07:11.985+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:07:11.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:07:12.014+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:07:12.013+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:07:12.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:07:12.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2024-01-23T17:07:42.424+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:07:42.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:07:42.430+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:07:42.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:07:42.467+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:07:42.466+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:07:42.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:07:42.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.066 seconds
[2024-01-23T17:08:12.814+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:08:12.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:08:12.819+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:08:12.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:08:12.856+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:08:12.855+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:08:12.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:08:12.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.065 seconds
[2024-01-23T17:08:43.198+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:08:43.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:08:43.204+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:08:43.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:08:43.239+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:08:43.238+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:08:43.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:08:43.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.062 seconds
[2024-01-23T17:09:13.552+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:09:13.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:09:13.556+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:09:13.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:09:13.578+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:09:13.577+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:09:13.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:09:13.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2024-01-23T17:09:43.884+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:09:43.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:09:43.887+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:09:43.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:09:43.911+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:09:43.910+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:09:43.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:09:43.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2024-01-23T17:10:14.224+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:10:14.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:10:14.228+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:10:14.228+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:10:14.262+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:10:14.261+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:10:14.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:10:14.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.059 seconds
[2024-01-23T17:10:44.516+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:10:44.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:10:44.521+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:10:44.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:10:44.554+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:10:44.553+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:10:44.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:10:44.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.057 seconds
[2024-01-23T17:11:14.824+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:11:14.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:11:14.827+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:11:14.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:11:14.851+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:11:14.850+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:11:14.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:11:14.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2024-01-23T17:11:45.206+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:11:45.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:11:45.211+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:11:45.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:11:45.245+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:11:45.245+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:11:45.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:11:45.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.060 seconds
[2024-01-23T17:12:15.522+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:12:15.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:12:15.527+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:12:15.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:12:15.557+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:12:15.556+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:12:15.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:12:15.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.053 seconds
[2024-01-23T17:12:45.909+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:12:45.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:12:45.913+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:12:45.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:12:45.944+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:12:45.943+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:12:45.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:12:45.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.055 seconds
[2024-01-23T17:13:16.269+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:13:16.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:13:16.274+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:13:16.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:13:16.317+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:13:16.316+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:13:16.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:13:16.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.069 seconds
[2024-01-23T17:13:46.766+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:13:46.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:13:46.772+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:13:46.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:13:46.810+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:13:46.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:13:46.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:13:46.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.064 seconds
[2024-01-23T17:14:17.156+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:14:17.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:14:17.162+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:14:17.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:14:17.196+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:14:17.195+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:14:17.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:14:17.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.061 seconds
[2024-01-23T17:14:47.559+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:14:47.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:14:47.563+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:14:47.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:14:47.591+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:14:47.590+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:14:47.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:14:47.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2024-01-23T17:17:36.473+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:17:36.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:17:36.479+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:17:36.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:17:36.509+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:17:36.507+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:17:36.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:17:36.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.056 seconds
[2024-01-23T17:48:25.240+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:48:25.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T17:48:25.244+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:48:25.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:48:25.273+0000] {logging_mixin.py:188} INFO - [2024-01-23T17:48:25.272+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T17:48:25.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T17:48:25.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2024-01-23T18:33:42.395+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T18:33:42.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T18:33:42.413+0000] {logging_mixin.py:188} INFO - [2024-01-23T18:33:42.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T18:33:42.505+0000] {logging_mixin.py:188} INFO - [2024-01-23T18:33:42.500+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T18:33:42.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T18:33:42.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.180 seconds
[2024-01-23T18:56:51.646+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T18:56:51.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T18:56:51.651+0000] {logging_mixin.py:188} INFO - [2024-01-23T18:56:51.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T18:56:51.743+0000] {logging_mixin.py:188} INFO - [2024-01-23T18:56:51.738+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T18:56:51.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T18:56:51.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.147 seconds
[2024-01-23T20:16:57.276+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T20:16:57.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T20:16:57.282+0000] {logging_mixin.py:188} INFO - [2024-01-23T20:16:57.282+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T20:16:57.335+0000] {logging_mixin.py:188} INFO - [2024-01-23T20:16:57.328+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T20:16:57.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T20:16:57.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.103 seconds
[2024-01-23T21:16:02.070+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T21:16:02.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T21:16:02.075+0000] {logging_mixin.py:188} INFO - [2024-01-23T21:16:02.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T21:16:02.118+0000] {logging_mixin.py:188} INFO - [2024-01-23T21:16:02.117+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T21:16:02.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T21:16:02.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.071 seconds
[2024-01-23T22:39:04.681+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/spotify_dag.py
[2024-01-23T22:39:04.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2024-01-23T22:39:04.690+0000] {logging_mixin.py:188} INFO - [2024-01-23T22:39:04.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2024-01-23T22:39:04.726+0000] {logging_mixin.py:188} INFO - [2024-01-23T22:39:04.725+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_utils import Spotify
  File "/opt/airflow/dags/spotify_utils/__init__.py", line 5, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
[2024-01-23T22:39:04.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2024-01-23T22:39:04.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.076 seconds
